package downloader;

public class Window extends javax.swing.JFrame
{

    javax.swing.JButton btnAdd;
    javax.swing.JButton btnClearAll;
    javax.swing.JButton btnRemoveSelected;
    javax.swing.JButton btnReset;
    javax.swing.JList<String> jList;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JSeparator jSeparator1;
    javax.swing.JMenuItem mnChangeDownloadTime;
    javax.swing.JMenu mnFile;
    javax.swing.JMenuItem mnSetDownloadDirectory;
    javax.swing.JTextField txtURL;
    Main main;
    
    public Window(Main main)
    {
        this.main = main;
        setLookAndFeel();
        initComponents();
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        txtURL = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemoveSelected = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnSetDownloadDirectory = new javax.swing.JMenuItem();
        mnChangeDownloadTime = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList.setModel(main.urlList.listModel);
        jScrollPane1.setViewportView(jList);

        txtURL.setText(GUI.DEFAULT_TXT);
        txtURL.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtURLFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtURLFocusLost(evt);
            }
        });
        txtURL.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtURLActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddActionPerformed(evt);
            }
        });

        btnRemoveSelected.setText("Remove Selected");
        btnRemoveSelected.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemoveSelectedActionPerformed(evt);
            }
        });

        btnClearAll.setText("Clear All");
        btnClearAll.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnClearAllActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnResetActionPerformed(evt);
            }
        });

        mnFile.setText("File");

        mnSetDownloadDirectory.setText("Set Download Directory");
        mnSetDownloadDirectory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnSetDownloadDirectoryActionPerformed(evt);
            }
        });
        mnFile.add(mnSetDownloadDirectory);

        mnChangeDownloadTime.setText("Change Download Time");
        mnChangeDownloadTime.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnChangeDownloadTimeActionPerformed(evt);
            }
        });
        mnFile.add(mnChangeDownloadTime);

        jMenuBar1.add(mnFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClearAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoveSelected)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtURL, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveSelected)
                    .addComponent(btnClearAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddActionPerformed
    {//GEN-HEADEREND:event_btnAddActionPerformed
        main.gui.addAction();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnResetActionPerformed
    {//GEN-HEADEREND:event_btnResetActionPerformed
        main.gui.resetAction();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtURLActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtURLActionPerformed
    {//GEN-HEADEREND:event_txtURLActionPerformed
        main.gui.addAction();
    }//GEN-LAST:event_txtURLActionPerformed

    private void btnRemoveSelectedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveSelectedActionPerformed
    {//GEN-HEADEREND:event_btnRemoveSelectedActionPerformed
        main.gui.removeSelectedAction();
    }//GEN-LAST:event_btnRemoveSelectedActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearAllActionPerformed
    {//GEN-HEADEREND:event_btnClearAllActionPerformed
        main.gui.clearAllAction();
    }//GEN-LAST:event_btnClearAllActionPerformed

    private void mnSetDownloadDirectoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnSetDownloadDirectoryActionPerformed
    {//GEN-HEADEREND:event_mnSetDownloadDirectoryActionPerformed
        main.gui.setDirectory();
    }//GEN-LAST:event_mnSetDownloadDirectoryActionPerformed

    private void mnChangeDownloadTimeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnChangeDownloadTimeActionPerformed
    {//GEN-HEADEREND:event_mnChangeDownloadTimeActionPerformed
        main.gui.setDownloadTime();
    }//GEN-LAST:event_mnChangeDownloadTimeActionPerformed

    private void txtURLFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtURLFocusLost
    {//GEN-HEADEREND:event_txtURLFocusLost
        main.gui.txtUrlFocusLost();
    }//GEN-LAST:event_txtURLFocusLost

    private void txtURLFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtURLFocusGained
    {//GEN-HEADEREND:event_txtURLFocusGained
        main.gui.txtUrlFocusGained();
    }//GEN-LAST:event_txtURLFocusGained

    private void setLookAndFeel()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnRemoveSelected;
    private javax.swing.JButton btnReset;
    private javax.swing.JList<String> jList;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem mnChangeDownloadTime;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnSetDownloadDirectory;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
*/
}
